USE master
GO
DROP DATABASE CSDLFN
GO
CREATE DATABASE CSDLFN
GO
USE CSDLFN
GO
CREATE TABLE ADMINS
(
	MaADMIN varchar(10)primary key,
	HoTen nvarchar(100),
	cmdn varchar(10),
	email varchar(1000)
)
CREATE TABLE Hocsinh
(
	MaHS VARCHAR(10) PRIMARY KEY, 
	HoTen NVARCHAR(50), 
	NgaySinh DATETIME, 
	SDT VARCHAR(10),
	Email VARCHAR(150),
	DiaChi NVARCHAR(120),  
	MaLop VARCHAR(10)
)
CREATE TABLE GiaoVIen
(
	MaGV VARCHAR(10) PRIMARY KEY, 
	HoTen NVARCHAR(50), 
	NgaySinh DATETIME, 
	SDT VARCHAR(10),
	Email VARCHAR(150),
	DiaChi NVARCHAR(120),
	MaBM VARCHAR(10)
)
CREATE TABLE BoMon
(
	MaBM VARCHAR(10) PRIMARY KEY, 
	TenBM NVARCHAR(50), 
	ChuNhiem VARCHAR(10)
)
CREATE TABLE Khoi
( 
	MaKhoi VARCHAR(10) PRIMARY KEY, 
	TenKhoi VARCHAR(10), 
	TruongKhoi VARCHAR(10)
)
CREATE TABLE Lop
(	
	MaLop VARCHAR(10) PRIMARY KEY, 
	MaKhoi VARCHAR(10), 
	NamHoc INT, 
	GVCN VARCHAR(10)
)
CREATE TABLE LoaiTK
( 
	MaLoai VARCHAR(5) PRIMARY KEY, 
	Loai INT,
	TenLoai NVARCHAR(20)
)
CREATE TABLE TaiKhoan
(
	MaTK INT IDENTITY(1,1) PRIMARY KEY,
	UserName VARCHAR(50), 
	SPassWord VARCHAR(100), 
	MaLoai VARCHAR(5), 
	MaNguoiDung VARCHAR(100)
)
CREATE TABLE KQThi
(
	MaTK INT, 
	LanThi INT IDENTITY(1,1),
	MonThi VARCHAR(10), 
	DiemThi FLOAT
	CONSTRAINT PK_KQTHI PRIMARY KEY (MATK,LANTHI,MONTHI)
)
CREATE TABLE CauHoiDongGop
(
	MaTK INT,
	STT INT IDENTITY(1,1), 
	MonHoc VARCHAR(10), 
	CapHoc VARCHAR(10), 
	TinhTrang BIT DEFAULT(0)
	CONSTRAINT PK_CHDG PRIMARY KEY (MATK,STT)
)
CREATE TABLE LoaiCauHoi
(
	MaLoai VARCHAR(5) PRIMARY KEY, 
	DoKho INT	
)
CREATE TABLE ChiTietCauHoi
(
	MaCH INT IDENTITY(1,1) PRIMARY KEY,
	MaTK INT,
	STT INT,
	NoiDungCauHoi NVARCHAR(1000), 
	DoKho INT, 
	DapAnA NVARCHAR(500),
	DapAnB NVARCHAR(500),
	DapAnC NVARCHAR(500),
	DapAnD NVARCHAR(500)
)
CREATE TABLE LichSuSD
(
	MaCH INT, 
	MaDe VARCHAR(10), 
	Ngay DATETIME
)
ALTER TABLE LichSuSD
ADD CONSTRAINT PK_LS_CH FOREIGN KEY(MaCH)
REFERENCES ChiTietCauHoi(MaCH)
ALTER TABLE HOCSINH
ADD CONSTRAINT PK_HS_LOP FOREIGN KEY(MALOP)
REFERENCES LOP(MALOP)
ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GV_BM FOREIGN KEY(MABM)
REFERENCES BOMON(MABM)
ALTER TABLE BOMON
ADD CONSTRAINT PK_BM_GV FOREIGN KEY(CHUNHIEM)
REFERENCES GIAOVIEN(MAGV)
ALTER TABLE KHOI
ADD CONSTRAINT PK_KHOI_GV FOREIGN KEY(TruongKhoi)
REFERENCES GIAOVIEN(MAGV)
ALTER TABLE LOP
ADD CONSTRAINT PK_LOP_GV FOREIGN KEY(GVCN)
REFERENCES GIAOVIEN(MAGV)
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK_LTK FOREIGN KEY(MaLoai)
REFERENCES LoaiTK(MaLoai)
ALTER TABLE KQTHI
ADD CONSTRAINT PK_KQT_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)
ALTER TABLE CauHoiDongGop
ADD CONSTRAINT PK_CHDG_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)
ALTER TABLE CauHoiDongGop
ADD CONSTRAINT PK_CHDG_BM FOREIGN KEY(MonHoc)
REFERENCES BoMon(MaBM)
ALTER TABLE CauHoiDongGop
ADD CONSTRAINT PK_CHDG_Khoi FOREIGN KEY(CapHoc)
REFERENCES Khoi(MaKhoi)
ALTER TABLE ChiTietCauHoi
ADD CONSTRAINT PK_CTCH_CHDG FOREIGN KEY(MaTK,STT)
REFERENCES CauHoiDongGop(MaTK,STT)
------------------------------------------
--INSERT DỮ LIỆU
INSERT INTO ADMINS VALUES('ADM001',N'Nguyễn Nhật Ninh','1234567890','anthuylinh999@gmail.com')
INSERT INTO LoaiTK VALUES('TKL1',1,N'ADMIN'),('TKL2',2,N'Giáo viên'),('TKL3',3,N'Học sinh')
INSERT INTO TaiKhoan VALUES('nincute99','123456','TKL1','ADM001')
select * from TaiKhoan