CREATE DATABASE CSDLFN
GO
USE CSDLFN
GO
CREATE TABLE Hocsinh
(
	MaHS VARCHAR(10) PRIMARY KEY, 
	HoTen NVARCHAR(50), 
	NgaySinh DATETIME, 
	SDT VARCHAR(10),
	Email VARCHAR(150),
	DiaChi NVARCHAR(120),  
	MaLop VARCHAR(10)
)
CREATE TABLE GiaoVIen
(
	MaGV VARCHAR(10) PRIMARY KEY, 
	HoTen NVARCHAR(50), 
	NgaySinh DATETIME, 
	SDT VARCHAR(10),
	Email VARCHAR(150),
	DiaChi NVARCHAR(120),
	MaBM VARCHAR(10)
)
CREATE TABLE DanhSachBM
(
	MaBM VARCHAR(10) PRIMARY KEY, 
	TenBM NVARCHAR(50), 
	ChuNhiem VARCHAR(10)
)
CREATE TABLE Khoi
( 
	MaKhoi VARCHAR(10) PRIMARY KEY, 
	TenKhoi VARCHAR(10), 
	TruongKhoi VARCHAR(10)
)
CREATE TABLE Lop
(	
	MaLop VARCHAR(10) PRIMARY KEY, 
	MaKhoi VARCHAR(10), 
	NamHoc INT, 
	ChuNhiemLop VARCHAR(10)
)
CREATE TABLE LoaiTK
( 
	MaLoai VARCHAR(5), 
	LoaiTK INT
)
CREATE TABLE TaiKhoan
(
	MaTK INT, 
	UserName VARCHAR(50) PRIMARY KEY, 
	SPassWord VARCHAR(100), 
	MaLoai VARCHAR(5), 
	MaNguoiDung VARCHAR(100)
)
CREATE TABLE KQThi
(
	MaTK INT, 
	LanThi INT, 
	MonThi VARCHAR(10), 
	DiemThi FLOAT
	CONSTRAINT PK_KQTHI PRIMARY KEY (MATK,LANTHI,MONTHI)
)
CREATE TABLE CauHoiDongGop
(
	MaTK INT, 
	MonHoc VARCHAR(10), 
	CapHoc VARCHAR(10), 
	TinhTrang BIT DEFAULT(0)
	CONSTRAINT PK_CHTG PRIMARY KEY (MATK,MONHOC,CAPHOC)
)
CREATE TABLE LoaiCauHoi
(
	MaLoai VARCHAR(5) PRIMARY KEY, 
	DoKho INT	
)
CREATE TABLE CacCauHoi
(
	MaCauHoi, 
	MaMonHoc, 
	MaLoai, 
	ThongTinCauHoi(CauHoi+DapAn)
)
CREATE TABLE LichSuSD
(
	MaCauHoi, 
	MaDe, 
	Ngay
)
